-- Create operators table (local players)
CREATE TABLE IF NOT EXISTS operators (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  callsign VARCHAR(50) UNIQUE NOT NULL,
  passcode_hash VARCHAR(255) NOT NULL,
  total_score INTEGER DEFAULT 0,
  current_level INTEGER DEFAULT 1,
  rank_position INTEGER,
  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NOW()
);

-- Create games table (game sessions)
CREATE TABLE IF NOT EXISTS games (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  operator_id UUID NOT NULL REFERENCES operators(id) ON DELETE CASCADE,
  level INTEGER NOT NULL,
  wpm INTEGER NOT NULL,
  accuracy DECIMAL(5,2) NOT NULL,
  score INTEGER NOT NULL,
  played_at TIMESTAMP DEFAULT NOW()
);

-- Create levels table
CREATE TABLE IF NOT EXISTS levels (
  number INTEGER PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  description TEXT,
  difficulty VARCHAR(20) NOT NULL,
  min_accuracy INTEGER NOT NULL DEFAULT 80,
  time_limit INTEGER NOT NULL DEFAULT 60
);

-- Create level_words table
CREATE TABLE IF NOT EXISTS level_words (
  id SERIAL PRIMARY KEY,
  level_number INTEGER NOT NULL REFERENCES levels(number) ON DELETE CASCADE,
  word TEXT NOT NULL
);

-- Create operator_played_words table
CREATE TABLE IF NOT EXISTS operator_played_words (
  operator_id UUID NOT NULL REFERENCES operators(id) ON DELETE CASCADE,
  word_id INTEGER NOT NULL REFERENCES level_words(id) ON DELETE CASCADE,
  level_number INTEGER NOT NULL,
  played_at TIMESTAMP DEFAULT NOW(),
  PRIMARY KEY (operator_id, word_id)
);

-- Create leaderboard view
CREATE OR REPLACE VIEW leaderboard AS
SELECT 
  row_number() OVER (ORDER BY operators.current_level DESC, SUM(games.score) DESC, AVG(games.accuracy) DESC, MAX(games.wpm) DESC) as rank,
  operators.id,
  operators.callsign,
  operators.current_level,
  COALESCE(SUM(games.score), 0) as total_score,
  COUNT(games.id) as games_played,
  COALESCE(ROUND(AVG(games.accuracy)::numeric, 2), 0) as avg_accuracy,
  COALESCE(MAX(games.wpm), 0) as best_wpm
FROM operators
LEFT JOIN games ON operators.id = games.operator_id
GROUP BY operators.id, operators.callsign, operators.current_level
ORDER BY rank;

-- Create indexes for performance
CREATE INDEX IF NOT EXISTS idx_games_operator_id ON games(operator_id);
CREATE INDEX IF NOT EXISTS idx_games_level ON games(level);
CREATE INDEX IF NOT EXISTS idx_operators_callsign ON operators(callsign);
CREATE INDEX IF NOT EXISTS idx_level_words_level_number ON level_words(level_number);
CREATE INDEX IF NOT EXISTS idx_operator_played_words_operator_id_level ON operator_played_words(operator_id, level_number);

-- Seed Levels Metadata
INSERT INTO levels (number, name, description, difficulty, min_accuracy, time_limit) VALUES
(1, 'SECTOR ALPHA', 'Basic typing practice', 'Easy', 80, 60),
(2, 'SECTOR BETA', 'Technical terminology', 'Medium', 85, 50),
(3, 'SECTOR GAMMA', 'Advanced vocabulary', 'Hard', 90, 40)
ON CONFLICT (number) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  difficulty = EXCLUDED.difficulty,
  min_accuracy = EXCLUDED.min_accuracy,
  time_limit = EXCLUDED.time_limit;

-- Seed Level Words
DELETE FROM level_words WHERE level_number IN (1, 2, 3);

INSERT INTO level_words (level_number, word) VALUES
-- Level 1 Words
(1, 'the quick brown fox'),
(1, 'jumps over lazy dog'),
(1, 'fountain of youth'),
(1, 'crystal clear water'),
(1, 'midnight eclipse'),
(1, 'thundering clouds'),
(1, 'silver moonlight'),
(1, 'golden horizon'),
(1, 'electric storm'),
(1, 'frozen tundra'),
(1, 'a walk in the park'),
(1, 'a piece of cake'),
(1, 'an apple a day'),
(1, 'back to square one'),
(1, 'bite the bullet'),
(1, 'break a leg'),
(1, 'call it a day'),
(1, 'cut to the chase'),
(1, 'easy does it'),
(1, 'every cloud has a silver lining'),
(1, 'get a taste of your own medicine'),
(1, 'go down in flames'),
(1, 'hang in there'),
(1, 'hit the road'),
(1, 'in the same boat'),
(1, 'it takes two to tango'),
(1, 'jump on the bandwagon'),
(1, 'keep your chin up'),
(1, 'kill two birds with one stone'),
(1, 'let the cat out of the bag'),
(1, 'look before you leap'),
(1, 'miss the boat'),
(1, 'once in a blue moon'),
(1, 'play it by ear'),
(1, 'pull yourself together'),
(1, 'read between the lines'),
(1, 'save for a rainy day'),
(1, 'see eye to eye'),
(1, 'shoot for the stars'),
(1, 'sleep on it'),
(1, 'speak of the devil'),
(1, 'spill the beans'),
(1, 'stick to your guns'),
(1, 'take it with a grain of salt'),
(1, 'the ball is in your court'),
(1, 'the early bird gets the worm'),
(1, 'the sky is the limit'),
(1, 'throw in the towel'),
(1, 'time flies when you are having fun'),
(1, 'turn a blind eye'),
(1, 'under the weather'),
(1, 'waste not want not'),
(1, 'what goes around comes around'),
(1, 'when in Rome do as the Romans do'),
(1, 'you can say that again'),
(1, 'your guess is as good as mine'),
(1, 'a blessing in disguise'),
(1, 'add insult to injury'),
(1, 'barking up the wrong tree'),
(1, 'beat around the bush'),
(1, 'best of both worlds'),
(1, 'burn the midnight oil'),
(1, 'catch-22'),
(1, 'comparing apples and oranges'),
(1, 'cost an arm and a leg'),
(1, 'curiosity killed the cat'),
(1, 'cut corners'),
(1, 'devil in the details'),
(1, 'do not count your chickens before they hatch'),
(1, 'do not give up your day job'),
(1, 'do not put all your eggs in one basket'),
(1, 'down to the wire'),
(1, 'drive someone up a wall'),
(1, 'every dog has its day'),
(1, 'face the music'),
(1, 'fit as a fiddle'),
(1, 'get a second wind'),
(1, 'get your act together'),
(1, 'give the benefit of the doubt'),
(1, 'go back to the drawing board'),
(1, 'good things come to those who wait'),
(1, 'have a change of heart'),
(1, 'he who laughs last laughs longest'),
(1, 'heard it on the grapevine'),
(1, 'hit the nail on the head'),
(1, 'if it is not broke do not fix it'),
(1, 'in the heat of the moment'),
(1, 'it is not rocket science'),
(1, 'let sleeping dogs lie'),
(1, 'like a chicken with its head cut off'),
(1, 'make a long story short'),
(1, 'method to my madness'),
(1, 'never bite the hand that feeds you'),
(1, 'no pain no gain'),
(1, 'on the same page'),
(1, 'out of sight out of mind'),
(1, 'practice makes perfect'),
(1, 'put a sock in it'),
(1, 'put your best foot forward'),
(1, 'raining cats and dogs'),
(1, 'rock the boat'),
(1, 'run out of steam'),
(1, 'saved by the bell'),

-- Level 2 Words
(2, 'algorithmic complexity'),
(2, 'synchronization barrier'),
(2, 'authentication protocol'),
(2, 'computational efficiency'),
(2, 'distributed consensus'),
(2, 'asynchronous iteration'),
(2, 'cryptographic verification'),
(2, 'polymorphic inheritance'),
(2, 'abstraction layer'),
(2, 'optimization paradigm'),
(2, 'binary search algorithm'),
(2, 'dynamic programming approach'),
(2, 'object-oriented design'),
(2, 'functional programming paradigm'),
(2, 'relational database schema'),
(2, 'non-relational data store'),
(2, 'client-server architecture'),
(2, 'peer-to-peer network'),
(2, 'machine learning model'),
(2, 'deep neural network'),
(2, 'natural language processing'),
(2, 'computer vision system'),
(2, 'operating system kernel'),
(2, 'file system management'),
(2, 'memory allocation strategy'),
(2, 'process synchronization lock'),
(2, 'concurrent programming issue'),
(2, 'parallel computing cluster'),
(2, 'distributed version control'),
(2, 'continuous integration pipeline'),
(2, 'agile development methodology'),
(2, 'waterfall project management'),
(2, 'software development life cycle'),
(2, 'user interface design'),
(2, 'user experience research'),
(2, 'data structure and algorithm'),
(2, 'time complexity analysis'),
(2, 'space complexity analysis'),
(2, 'big O notation'),
(2, 'lambda calculus expression'),
(2, 'Turing machine simulation'),
(2, 'von Neumann architecture'),
(2, 'Harvard architecture'),
(2, 'RISC versus CISC'),
(2, 'instruction set architecture'),
(2, 'central processing unit'),
(2, 'graphics processing unit'),
(2, 'random access memory'),
(2, 'solid state drive'),
(2, 'hard disk drive'),
(2, 'network interface card'),
(2, 'motherboard chipset'),
(2, 'power supply unit'),
(2, 'cooling system fan'),
(2, 'case modification'),
(2, 'custom water cooling'),
(2, 'overclocking the processor'),
(2, 'under-volting the GPU'),
(2, 'RAID configuration'),
(2, 'network attached storage'),
(2, 'cloud computing service'),
(2, 'infrastructure as a service'),
(2, 'platform as a service'),
(2, 'software as a service'),
(2, 'serverless computing function'),
(2, 'microservices architecture'),
(2, 'monolithic application'),
(2, 'API gateway pattern'),
(2, 'load balancing strategy'),
(2, 'database sharding technique'),
(2, 'caching layer implementation'),
(2, 'content delivery network'),
(2, 'domain name system'),
(2, 'transport layer security'),
(2, 'secure shell protocol'),
(2, 'hypertext transfer protocol'),
(2, 'transmission control protocol'),
(2, 'internet protocol address'),
(2, 'media access control address'),
(2, 'local area network'),
(2, 'wide area network'),
(2, 'virtual private network'),
(2, 'firewall configuration'),
(2, 'intrusion detection system'),
(2, 'penetration testing'),
(2, 'vulnerability assessment'),
(2, 'threat modeling'),
(2, 'risk analysis'),
(2, 'disaster recovery plan'),
(2, 'business continuity plan'),
(2, 'service level agreement'),
(2, 'key performance indicator'),
(2, 'return on investment'),
(2, 'total cost of ownership'),
(2, 'minimum viable product'),
(2, 'proof of concept'),
(2, 'alpha testing phase'),
(2, 'beta testing phase'),
(2, 'general availability'),
(2, 'end of life'),
(2, 'deprecation notice'),
(2, 'legacy system migration'),
(2, 'data migration strategy'),
(2, 'ETL process'),
(2, 'data warehousing'),

-- Level 3 Words
(3, 'phenomenological transcendence'),
(3, 'serendipitous concatenation'),
(3, 'ineffable quintessence'),
(3, 'ubiquitous obfuscation'),
(3, 'perspicacious sublimation'),
(3, 'ostentatious manifestation'),
(3, 'ephemeral transfiguration'),
(3, 'inscrutable obfuscation'),
(3, 'evanescent luminescence'),
(3, 'mellifluous perambulation'),
(3, 'ontological argument for existence'),
(3, 'epistemological solipsism'),
(3, 'metaphysical dualism'),
(3, 'Kantian categorical imperative'),
(3, 'Nietzschean eternal recurrence'),
(3, 'Sartrean existential dread'),
(3, 'Foucauldian discourse analysis'),
(3, 'Derridean deconstruction'),
(3, 'Lacanian psychoanalytic theory'),
(3, 'Zizekian ideological critique'),
(3, 'Heideggerian Dasein'),
(3, 'Husserlian phenomenology'),
(3, 'Wittgensteinian language games'),
(3, 'Chomskyan generative grammar'),
(3, 'Gödelian incompleteness theorems'),
(3, 'Turing completeness proof'),
(3, 'P versus NP problem'),
(3, 'Riemann hypothesis'),
(3, 'Schrödinger wave equation'),
(3, 'Heisenberg uncertainty principle'),
(3, 'Einsteinian general relativity'),
(3, 'string theory and M-theory'),
(3, 'quantum entanglement'),
(3, 'Bohr model of the atom'),
(3, 'Maxwell equations of electromagnetism'),
(3, 'Newtonian laws of motion'),
(3, 'Leibnizian calculus notation'),
(3, 'Euclidean geometry'),
(3, 'non-Euclidean geometries'),
(3, 'fractal geometry and chaos theory'),
(3, 'Mandelbrot set'),
(3, 'game theory and Nash equilibrium'),
(3, 'Bayesian inference'),
(3, 'Markov chain Monte Carlo'),
(3, 'principal component analysis'),
(3, 'support vector machine'),
(3, 'k-means clustering algorithm'),
(3, 'genetic algorithm'),
(3, 'simulated annealing'),
(3, 'ant colony optimization'),
(3, 'particle swarm optimization'),
(3, 'artificial immune system'),
(3, 'cellular automaton'),
(3, 'emergent behavior'),
(3, 'complex adaptive system'),
(3, 'autopoiesis and self-organization'),
(3, 'cybernetics and control theory'),
(3, 'information theory and entropy'),
(3, 'signal processing and Fourier analysis'),
(3, 'cryptocurrency and blockchain'),
(3, 'decentralized autonomous organization'),
(3, 'smart contract execution'),
(3, 'zero-knowledge proof'),
(3, 'homomorphic encryption'),
(3, 'quantum computing and qubits'),
(3, 'superposition and interference'),
(3, 'quantum supremacy'),
(3, 'Bose-Einstein condensate'),
(3, 'superconductivity and superfluidity'),
(3, 'dark matter and dark energy'),
(3, 'cosmic microwave background radiation'),
(3, 'black hole information paradox'),
(3, 'holographic principle'),
(3, 'multiverse theory'),
(3, 'anthropic principle'),
(3, 'Fermi paradox'),
(3, 'Drake equation'),
(3, 'Kardashev scale'),
(3, 'Dyson sphere'),
(3, 'von Neumann probe'),
(3, 'terraforming and planetary engineering'),
(3, 'astrobiology and extremophiles'),
(3, 'panspermia hypothesis'),
(3, 'abiogenesis and the origin of life'),
(3, 'Masonic numerology'),
(3, 'theosophical esotericism'),
(3, 'hermeticism and alchemy'),
(3, 'gnosticism and the demiurge'),
(3, 'kabbalistic tree of life'),
(3, 'zodiacal astrology'),
(3, 'tarot divination'),
(3, 'I Ching hexagrams'),
(3, 'Vedic scriptures'),
(3, 'Upanishadic philosophy'),
(3, 'Buddhist concept of emptiness'),
(3, 'Taoist principle of Wu Wei'),
(3, 'Confucian ethics'),
(3, 'Shinto animism'),
(3, 'Norse mythology and Ragnarok'),
(3, 'Greek pantheon of gods'),
(3, 'Roman syncretism'),
(3, 'Egyptian book of the dead'),
(3, 'Mesopotamian cuneiform tablets'),
(3, 'Sumerian king list'),
(3, 'Epic of Gilgamesh');

